@url = http://localhost:5577/flashcards

### GET ALL
{{url}}

### GET SINGLE
{{url}}/3

### DELETE SINGLE
DELETE {{url}}/3

### POST SINGLE
POST {{url}}
content-type: application/json

{
	"category": "german",
	"front": "That is a house.",
	"back": "Das ist ein Haus."
}